import { app } from 'electron';
import { platform } from 'os';
import * as path from 'path';
export const appPath: string = app.getAppPath();
export const production: boolean = process.env.ELECTRON_ENV === 'production';
export const dataFolder: string = production ? path.join(appPath, '..', '..', 'data') : path.join(__dirname, '..', 'data');
export const controllerPath: string = path.join(dataFolder, 'disks.json');
export const disksFolder: string = path.join(dataFolder, 'disks');
export const appIcon: string = production ? path.join(appPath, '..', '..', 'logo.png') : path.join(__dirname, '..', 'assets', 'logo.png');
export const isLinux: boolean = platform() == 'linux';